package com.Zazsona.VoteItOut.game;

import java.util.LinkedList;
import java.util.Random;

public class Quips
{
    private static final String[] QUIPS = new String[]
            {
                    "Who would try to talk down the price of Girl Scout Cookies?",
                    "Who will show up to their high school reunion in a Lamborghini rental?",
                    "Who clogs the toilet at their friend's house and says nothing?",
                    "Whose Google search history would you like to see the most?",
                    "Who would have the hardest time talking their way out of an insane asylum?",
                    "Who will become really spiritual after a trip to Asia where they stayed at a 5-star hotel the whole time?",
                    "Who was the oldest when they stopped believing in Santa Claus?",
                    "Who seems like they were homeschooled?",
                    "Who will marry someone who isn't born yet?",
                    "Who will win the lottery but lose the ticket?",
                    "Who will get into a fight with an elderly person and lose?",
                    "Who has a secret crush on someone in the room?",
                    "Who would be your one phone call if you got arrested?",
                    "Who would survive the longest in a zombie apocalypse?",
                    "Who, if called upon, would be able to give the best toast right now?",
                    "Who is the most terrified of holding an infant?",
                    "Who doesn't believe that we put a man on the moon?",
                    "Who would be the best Walmart greeter?",
                    "Who will your great-grandchildren read about in school?",
                    "Who has watched a whole season of a TV show without leaving the house?",
                    "Who has thrown a birthday party for their dog or cat?",
                    "Who peaked in high school?",
                    "Who gets vanilla when they go to Ben and Jerry's?",
                    "Who has gotten bed sores from sitting on the couch?",
                    "Who would pay the most to add or subtract a couple inches to/from their height?",
                    "Who made the most money selling lemonade as a child?",
                    "Who pees in the pool?\n" +
                            "Every time.",
                    "Who could be the leader of a cult?",
                    "Who has fallen for a Nigerian Prince scam?",
                    "Who would do the best job singing the national anthem?",
                    "Who would fail a drug test right now?",
                    "Who is first in line for hell?",
                    "Who has more ropes than pillows in their bedroom?",
                    "Who is most likely to move to another country?",
                    "Who is most likely to have the most children?",
                    "Who is most likely to get cheated on?",
                    "Who would you ask for help if you needed to flee the country?",
                    "Who is smarter than people think?",
                    "Who would be the creepiest clown?",
                    "Who isn't wearing underwear right now?",
                    "Who would win a hotdog eating contest?",
                    "Who's standards drop the most after the first few drinks?",
                    "Who will resend a text if you haven't responded in 10 minutes?",
                    "Who's life would win best picture if it was turned into a film?",
                    "Who intimidates the opposite sex?",
                    "Who is most intimidated by the opposite sex?",
                    "Whose kids will need the most therapy?",
                    "Who would be considered the most attractive by a random stranger?",
                    "Who would vote for Kanye West as president?",
                    "Who missed the weed legalisation rally because they were too high?",
                    "Who would you vote for if we were all running for president?",
                    "Who has never voted for someone from the 'other' political party?",
                    "Who has been most offended during this game?",
                    "Who will have the police involved in their death?",
                    "Who would lose the election based on something they did in school?",
                    "Who drinks whiskey in their morning coffee?",
                    "Who has the most awkward school photo?",
                    "Who would be eaten first when the food runs out?",
                    "Who would you want as your mum or dad?",
                    "Who's insults deal only -1 HP?",
                    "Who regularly dreams about someone else in the room?",
                    "Who has spent the most time stalking their crush's Facebook page?",
                    "Who has seen the most players in the room naked?",
                    "Who would be the most willing to kiss the person to their right on the cards?",
                    "Who is the least trustworthy with a secret?",
                    "Who is the most trustworthy with a secret?",
                    "Who is obviously an only-child?",
                    "Who hangs out with the cat at a house party?",
                    "Who steals glasses from the pub/bar?",
                    "Who's nicked from a house party?",
                    "Who's got the most hours on YouTube meme compilations?",
                    "Who's still using MySpace?",
                    "Who has most recently wiped with something other than toilet paper?",
                    "Who is the most submissive?",
                    "Who gives the best life advice?",
                    "Who is secretly a superhero?",
                    "Who hits snooze on their alarm at least 5 times, before getting out of bed?",
                    "Who's keyboard has the most worn down WASD keys?",
                    "Who hates children most?",
                    "Who is on a terrorist watch list?",
                    "Who's last words will be \"Hold my beer while I...\"?",
                    "Who would marry for something other than love?",
                    "Who has been unfollowed the most on social media?",
                    "Who drops someone in a trust fall on purpose?",
                    "Whose moral compass is broken beyond repair?",
                    "Who has stolen money from a family member?",
                    "Who is stuck on an island because they have burned all their bridges?",
                    "Whose funeral will have the smallest attendance?",
                    "Who's least likely to be a target for identity theft?",
                    "Who's most likely to bring nothing to a B.Y.O.B party, but still enjoy what everyone else brought?",
                    "Who's most likely to lie about their age?",
                    "Who's most likely to have their friendliness misinterpreted as flirting?",
                    "Who's most likely to join a cult?",
                    "Who has the lowest standards?",
                    "Who making the 2AM call from jail tonight?",
                    "If we were all hitchhikers, who would be the last person to get picked up?",
                    "Who will be the most difficult old person to be around?",
                    "If we were all police officers, who would be the dirty cop?",
                    "Who's most likely to hook up with a close friend's ex?",
                    "Who's most likely to obey the voices in their head?",
                    "If you had to be someone else for the next 24 hours... Who would you least want to be?",
                    "Who would you most want to be for the next 24 hours?",
                    "Who's most likely to run into a former significant other and not remember their name?",
                    "If we were all stand-up comedians, who would get the least amount of laughs?",
                    "Who was the last person to have a drink thrown in their face?",
                    "Who's most likely to say \"I love you\" too early?",
                    "Who sleeps \"au natural\"?",
                    "Who looks better in person than in photos?",
                    "Who edits all their photos?",
                    "Who's hosting a new cooking show: \"All sweets. All the time.\"?",
                    "Who's got the best story about a wild party?",
                    "Who just never gets the reference?",
                    "Who's attempt at a candlelit dinner would just go up in flames?",
                    "Who's singing is the least like good singing?",
                    "Who is most frequently awake at 4AM?",
                    "Whose last photo on their phone is a selfie?",
                    "WHo got the highest exam scores in school?",
                    "Who believes money can buy happiness?",
                    "Who's the worst cook?",
                    "Who's the most likely to just mysteriously disappear one day?",
                    "Who's most likely to give Player 1 a big slap?",
                    "Who's most likely to spend hours on something, just to annoy Player 2?",
                    "Who has the most unapproachable face?",
                    "Who's happiest when they see someone they don't know fail?",
                    "Who's happiest when they see someone they don't know succeed?",
                    "If everyone was dressed as the opposite sex, who would be the most believable?",
                    "Who's most likely to fake a hearing problem, so they don't have to talk to their Uber driver?",
                    "Who would be the worst motivational speaker?",
                    "Who, given motivation, would punch a hole in their wall?",
                    "Who won't stop talking about their trip abroad?",
                    "Who always wants to play this stupid game?",
                    "Who would steal a street sign?",
                    "Who has the best chance of cheating a lie detector?",
                    "Who's most likely to lie about what they did last weekend?",
                    "Who's most likely to have a fake handicap for special treatment at an amusement park?",
                    "Who has the most vocal toilet sessions?",
                    "Who's most likely to win the lottery and blow it all?",
                    "Who's most likely to tell people that they're an Instagram model?",
                    "For £100, who's most likely to tell a child Santa isn't real?",
                    "Who thinks they're the most intelligent person in the room?",
                    "Who is never able to complete a project?",
                    "Who's the flaker when planning a meetup?",
                    "Who's also doing something else right now?",
                    "Who's the closet weeb?",
                    "Who could easily sleep a full 24 hours without an alarm?",
                    "Who's starts every day with children's cereal?",
                    "Who's got the most secrets?",
                    "Who would you be most scared of if they were walking towards you in a dark alley?",
                    "Who's the crazy cat person?",
                    "Who's trying to find a way to cheat in this game?",
                    "Who's the most extra, and tries to give too much flair to everything they do?",
                    "Who's now consciously breathing through their nose?",
                    "Who's always got a trick up their sleeves?",
                    "WHo just seems to trip at every hurdle?",
                    "Who's into crossdressing?",
                    "Everyone's been caught by the police. Who do you nominate to talk you out of trouble?",
                    "Let's start a pirate crew! Who's the captain?",
                    "Who can most often to found twiddling their thumbs?",
                    "Who most needs some hearing aids?",
                    "Who's got a different persona for every occasion?",
                    "Who's the most fun to mess with?",
                    "Who's always not-so-fashionably late?",
                    "Who's the most avid dreamer?",
                    "Let's say we were to kick someone out the game. Who's going?",
                    "Vote for anyone.",
                    "Who tries the arm around trick on a first date?",
                    "Who's most likely to secretly know another language?",
                    "Who hangs around with rubber ducks in the bath?",
                    "Who's watching YouTube right now?",
                    "WHo could convince anyone of anything?",
                    "Who's gone the longest without a shower or bath?",
                    "Who's the most technologically inept?",
                    "Who's only here because they crave the attention?",
                    "Who was a regular resident of the naughty step as a kid?",
                    "Who's the most innocent person in the room?",
                    "Who's undoubtedly eating something right now?",
                    "Who waits loves Valentine's Day for the post-event chocolate sales?",
                    "Who's look doesn't match their personality?",
                    "Who checks the gas, the burglar alarm, the window, and all else before you can finally get them to leave the house?",
                    "Who's secretly fuming right now?",
                    "Who's not matured since they were 13?",
                    "Who's always buying cheap tat on eBay?",
                    "Who's a secret agent reporting back on the activities of everyone in the room?",
                    "Who's the biggest basement dweller?"
            };
    private static final String[] NSFW_QUIPS = new String[]
            {
                    "Who has used something as a sex toy that is normally reserved for eating?",
                    "Who would be the first picked for a threesome?",
                    "Who has a Costco size pack of expired condoms?",
                    "Who has left the most comments on porn videos?",
                    "Who will be having the most sex in the retirement home?",
                    "Who would have owned the most slaves if they lived in 1800?",
                    "Who has spent the most time grooming their pubic hair?",
                    "Who would have made an excellent Nazi?",
                    "Who is most likely to have sex most often?",
                    "Who burns the least amount of calories during sex?",
                    "Who has sent a nude picture to someone they met online?",
                    "Who can you find naked on the internet?",
                    "Who will still be an arsehole in 10 years?",
                    "Who never reciprocates oral sex?",
                    "Who has screamed the wrong name during sex?",
                    "Who has to schedule sex with their significant other?",
                    "Who has the hairiest genitals?",
                    "Who's the most ashamed of their porn search history?",
                    "Who lost their virginity at the youngest age?",
                    "Who will wait the longest before they have sex again?",
                    "Who would rather be killed than paralyzed?",
                    "Who would have the highest kill count in World War III?",
                    "Who wins the gold medal for cock blocking?",
                    "Who has the most in common with Hitler?",
                    "Who has purchased drugs from a stranger?",
                    "Who has responded to a sexual inquiry on Craigslist?",
                    "Who is the loudest in the bedroom?",
                    "Who's sex life would get the most views on a porn site?",
                    "Who's had a wank most recently?",
                    "Who is the most turned on by two dogs humping in the park?",
                    "Who has most recently put something up their arse?",
                    "Who fits the stereotype of a race other than their own?",
                    "If we were all in prison, who's most likely to become someone's bitch?",
                    "Who would be the worst phone sex operator?",
                    "Who would be the best phone sex operator?",
                    "Most likely to secretly run a meth lab?",
                    "Who's most likely to laugh if they saw a blind person trip?",
                    "Who's most likely to get a quick wank in the work bathrooms?",
                    "Who's most likely to get down to business with their cousin?",
                    "Who's most likely to try anal bleaching?",
                    "Whose genitals are the prettiest?",
                    "Who has the most convincing fake orgasm?",
                    "Who would be willing to have sex with the highest number of people in the room?",
                    "Who would try to pay for sex with spare change?",
                    "Who has a dedicated sex 'n' wanking drawer?",
                    "Who's most likely to take a shit on their lover's chest?",
                    "Who's most likely to be secretly homophobic?",
                    "Who's fucking idea was this shit?",
                    "Who would hook up with someone, just because of their accent?",
                    "Who's the most desperate?",
                    "Who's least likely to participate in a threesome?"
            };

    private LinkedList<Integer> usedQuestions;

    public Quips()
    {
        usedQuestions = new LinkedList<>();
    }

    public String getQuip(boolean nsfw)
    {
        Random r = new Random();
        int maxValue = (nsfw) ? QUIPS.length+NSFW_QUIPS.length : QUIPS.length;
        int quipID = -1;
        while (quipID == -1 || usedQuestions.contains(quipID))
            quipID = r.nextInt(maxValue);
        usedQuestions.add(quipID);
        if (quipID < QUIPS.length)
        {
            return QUIPS[quipID];
        }
        else
        {
            return NSFW_QUIPS[(quipID-QUIPS.length)];
        }
    }
}
